(function () {
  function q(id){return document.getElementById(id);}
  function formatINR(v){if(!isFinite(v))return"—";return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Math.round(v));}
  function formatCompactINR(v){if(!isFinite(v))return"—";var a=Math.abs(v);if(a>=1e7)return"₹"+(v/1e7).toFixed(v>=1e8?0:1)+" Cr";if(a>=1e5)return"₹"+(v/1e5).toFixed(v>=1e6?0:1)+" L";return formatINR(v);}
  function setupCanvas(c){if(!c)return null;var r=c.getBoundingClientRect(),d=window.devicePixelRatio||1,w=Math.max(280,Math.floor(r.width)),h=Math.max(220,Math.floor(r.height||260));c.width=w*d;c.height=h*d;var x=c.getContext("2d");x.setTransform(d,0,0,d,0,0);return{ctx:x,width:w,height:h};}
  function rr(ctx,x,y,w,h,r){var n=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+n,y);ctx.lineTo(x+w-n,y);ctx.quadraticCurveTo(x+w,y,x+w,y+n);ctx.lineTo(x+w,y+h-n);ctx.quadraticCurveTo(x+w,y+h,x+w-n,y+h);ctx.lineTo(x+n,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-n);ctx.lineTo(x,y+n);ctx.quadraticCurveTo(x,y,x+n,y);ctx.closePath();}
  function today(){var n=new Date(),o=n.getTimezoneOffset()*60000;return new Date(n.getTime()-o).toISOString().slice(0,10);}
  function createRow(d,i,w){var tr=document.createElement("tr");tr.className="iv-xirr-cashflow-row";tr.innerHTML='<td><input class="iv-xirr-table-input iv-xirr-date" type="date"></td><td><input class="iv-xirr-table-input iv-xirr-invested" type="number" min="0"></td><td><input class="iv-xirr-table-input iv-xirr-withdrawn" type="number" min="0"></td><td><button class="iv-xirr-delete" type="button">Delete</button></td>'; if(d)tr.querySelector(".iv-xirr-date").value=d; if(i!==undefined)tr.querySelector(".iv-xirr-invested").value=i; if(w!==undefined)tr.querySelector(".iv-xirr-withdrawn").value=w; return tr;}
  function bindDelete(row,body){var b=row.querySelector(".iv-xirr-delete"); if(!b||b._ivBound)return; b._ivBound=true; b.addEventListener("click",function(){var rows=body.querySelectorAll(".iv-xirr-cashflow-row"); if(rows.length<=1){row.querySelectorAll("input").forEach(function(i){i.value="";});}else row.remove();});}
  function npv(rate,cfs){var start=cfs[0].date; return cfs.reduce(function(sum,cf){var y=(cf.date-start)/(365.25*24*60*60*1000); return sum+cf.amount/Math.pow(1+rate,y);},0);}
  function calcRate(cfs){var low=-0.999999,high=10,nl=npv(low,cfs),nh=npv(high,cfs),k=0; while(nl*nh>0&&k<30){high=high*2+1;nh=npv(high,cfs);k++;} if(!isFinite(nl)||!isFinite(nh)||nl*nh>0) return null; for(var i=0;i<120;i++){var mid=(low+high)/2,nm=npv(mid,cfs); if(!isFinite(nm))return null; if(Math.abs(nm)<0.000001)return mid; if(nl*nm<=0){high=mid;nh=nm;}else{low=mid;nl=nm;}} return (low+high)/2;}
  function perf(x){ if(x<8)return{category:"Extremely weak equity performance",message:"Performance is materially weak. Review process and risk management."}; if(x<15)return{category:"Below-average equity performance",message:"Below long-term target range for serious equity investors."}; if(x<25)return{category:"Good equity performance",message:"Good trajectory. Improve allocation and risk control for consistency."}; return{category:"Excellent equity performance",message:"Strong investing process. Keep tracking risk and avoid overconfidence."};}
  function collect(body,current,vd){var rows=[].slice.call(body.querySelectorAll(".iv-xirr-cashflow-row")),cashflows=[],ti=0,tw=0,hasInv=false; for(var i=0;i<rows.length;i++){var r=rows[i],date=r.querySelector(".iv-xirr-date").value,ir=r.querySelector(".iv-xirr-invested").value,wr=r.querySelector(".iv-xirr-withdrawn").value,any=date||ir||wr; if(!any)continue; if(!date)return{error:"Dates are required for all filled cashflow rows."}; var inv=ir===""?0:Number(ir),wd=wr===""?0:Number(wr); if(!isFinite(inv)||inv<0||!isFinite(wd)||wd<0)return{error:"Amounts must be non-negative."}; if(inv===0&&wd===0)return{error:"Enter invested or withdrawn amount for each filled row."}; if(inv>0){cashflows.push({date:new Date(date+"T00:00:00"),amount:-inv,label:"Investment"});ti+=inv;hasInv=true;} if(wd>0){cashflows.push({date:new Date(date+"T00:00:00"),amount:wd,label:"Withdrawal"});tw+=wd;}}
    var ccRaw=current.value,cc=Number(ccRaw),v=vd.value; if(!hasInv)return{error:"At least one investment entry is required."}; if(ccRaw===""||!isFinite(cc)||cc<0)return{error:"Current capital is required and must be non-negative."}; if(!v)return{error:"Valuation date is required."}; cashflows.push({date:new Date(v+"T00:00:00"),amount:cc,label:"Current Value"}); var neg=cashflows.some(function(c){return c.amount<0;}),pos=cashflows.some(function(c){return c.amount>0;}); if(!neg||!pos)return{error:"Need at least one investment and one positive cashflow."}; cashflows.sort(function(a,b){return a.date-b.date;}); return{cashflows:cashflows,totalInvested:ti,totalWithdrawn:tw,currentCapital:cc};}
  function drawJourney(canvas,pts){var d=setupCanvas(canvas); if(!d||!pts.length)return; var c=d.ctx,w=d.width,h=d.height,pL=w<420?44:58,pR=16,pT=18,pB=36,pW=w-pL-pR,pH=h-pT-pB,max=Math.max.apply(null,pts.map(function(p){return Math.max(p.deployed||0,p.value||0);}))*1.12; if(max<=0)max=1,start=pts[0].date.getTime(),end=pts[pts.length-1].date.getTime(); if(end===start)end=start+86400000; function x(dt){return pL+((dt.getTime()-start)/(end-start))*pW;} function y(v){return pT+pH-(v/max)*pH;}
    c.clearRect(0,0,w,h); c.strokeStyle="rgba(255,255,255,0.08)"; c.fillStyle="rgba(203,213,232,0.72)"; c.font="10px Inter, Arial";
    for(var g=0;g<=4;g++){var yy=pT+(pH*g/4),val=max*(1-g/4); c.beginPath(); c.moveTo(pL,yy); c.lineTo(w-pR,yy); c.stroke(); c.fillText(formatCompactINR(val),4,yy+3);}
    c.beginPath(); pts.forEach(function(p,i){var xx=x(p.date),yy=y(p.deployed); if(i===0)c.moveTo(xx,yy); else c.lineTo(xx,yy);}); c.strokeStyle="#4C8DFF"; c.lineWidth=2.4; c.stroke();
    var f=pts[pts.length-1]; c.fillStyle="#D4AF37"; c.beginPath(); c.arc(x(f.date),y(f.value),5,0,Math.PI*2); c.fill();
    canvas._pts=pts.map(function(p){return{x:x(p.date),date:p.date,deployed:p.deployed,value:p.value,label:p.label};});
  }
  function drawSummary(canvas,s){var d=setupCanvas(canvas); if(!d)return; var c=d.ctx,w=d.width,h=d.height,pL=w<420?44:58,pR=16,pT=18,pB=48,pW=w-pL-pR,pH=h-pT-pB,b=[{label:"Invested",value:s.totalInvested,color:"#4C8DFF"},{label:"Withdrawn",value:s.totalWithdrawn,color:"#77DD77"},{label:"Current",value:s.currentCapital,color:"#D4AF37"},{label:"Gain/Loss",value:s.absoluteGainLoss,color:s.absoluteGainLoss>=0?"#D4AF37":"#FF6B6B"}],max=Math.max.apply(null,b.map(function(v){return Math.abs(v.value);}))*1.15; if(max<=0)max=1; var gap=12,bw=Math.max(24,(pW-gap*(b.length-1))/b.length),base=pT+pH; c.clearRect(0,0,w,h);
    b.forEach(function(v,i){var x=pL+i*(bw+gap),hh=(Math.abs(v.value)/max)*pH; c.fillStyle=v.color; rr(c,x,base-hh,bw,Math.max(2,hh),6); c.fill(); c.fillStyle="rgba(203,213,232,0.82)"; c.fillText(v.label,x,h-22);});
    canvas._bars=b.map(function(v,i){return{x:pL+i*(bw+gap),w:bw,label:v.label,value:v.value};});
  }
  document.addEventListener("DOMContentLoaded",function(){
    var body=q("ivXirrCashflowBody"),add=q("ivXirrAddRow"),cc=q("ivXirrCurrentCapital"),vd=q("ivXirrValuationDate"),calc=q("ivXirrCalculate"),reset=q("ivXirrReset"),err=q("ivXirrError"),res=q("ivXirrResult"),cat=q("ivXirrCategory"),ti=q("ivXirrTotalInvested"),tw=q("ivXirrTotalWithdrawn"),nd=q("ivXirrNetDeployed"),co=q("ivXirrCurrentOut"),gl=q("ivXirrGainLoss"),msg=q("ivXirrMessage"),jc=q("ivXirrJourneyChart"),sc=q("ivXirrSummaryChart"),tt=q("ivXirrTooltip");
    if(!body) return;
    function show(m){err.textContent=m; err.style.display=m?"block":"none";}
    function bindRows(){body.querySelectorAll(".iv-xirr-cashflow-row").forEach(function(r){bindDelete(r,body);});}
    function run(){var collected=collect(body,cc,vd); if(collected.error){show(collected.error);return;} var rate=calcRate(collected.cashflows); if(rate===null||!isFinite(rate)){show("XIRR could not be calculated. Please check entries."); return;} show(""); var x=rate*100,net=collected.totalInvested-collected.totalWithdrawn,ag=collected.currentCapital+collected.totalWithdrawn-collected.totalInvested,p=perf(x),deployed=0,pts=[]; collected.cashflows.forEach(function(cf){if(cf.amount<0)deployed+=Math.abs(cf.amount); if(cf.label==="Withdrawal")deployed-=cf.amount; if(cf.label!=="Current Value")pts.push({date:cf.date,deployed:deployed,value:null,label:cf.label});}); var cur=collected.cashflows[collected.cashflows.length-1]; pts.push({date:cur.date,deployed:deployed,value:cur.amount,label:"Current Value"});
      res.textContent=x.toFixed(2)+"%"; cat.textContent=p.category; ti.textContent=formatINR(collected.totalInvested); tw.textContent=formatINR(collected.totalWithdrawn); nd.textContent=formatINR(net); co.textContent=formatINR(collected.currentCapital); gl.textContent=formatINR(ag); msg.textContent=p.message;
      drawJourney(jc,pts); drawSummary(sc,{totalInvested:collected.totalInvested,totalWithdrawn:collected.totalWithdrawn,currentCapital:collected.currentCapital,absoluteGainLoss:ag});
    }
    function resetAll(){body.innerHTML=""; body.appendChild(createRow("","","")); bindRows(); cc.value=""; vd.value=today(); show(""); [res,cat,ti,tw,nd,co,gl].forEach(function(el){el.textContent="—";}); msg.textContent="Enter cashflows and current capital to calculate your annualized portfolio return."; [jc,sc].forEach(function(cv){var d=setupCanvas(cv); if(d)d.ctx.clearRect(0,0,d.width,d.height);}); if(tt)tt.style.display="none";}
    vd.value=today(); bindRows();
    if(add&&!add._ivBound){add._ivBound=true; add.addEventListener("click",function(){body.appendChild(createRow("","","")); bindRows();});}
    calc.addEventListener("click",run); if(reset)reset.addEventListener("click",resetAll);
    [cc,vd].forEach(function(i){i&&i.addEventListener("keydown",function(e){if(e.key==="Enter")run();});});
    function move(canvas,mode,e){if(!tt||!canvas)return; var r=canvas.getBoundingClientRect(),x=e.clientX-r.left,d=null; if(mode==="journey"&&canvas._pts){canvas._pts.forEach(function(p){if(!d||Math.abs(p.x-x)<Math.abs(d.x-x))d=p;}); if(d)tt.innerHTML="<b>"+d.label+"</b><br>Date: "+d.date.toISOString().slice(0,10)+"<br>Net deployed: "+formatINR(d.deployed)+(d.value!==null?"<br>Current value: "+formatINR(d.value):"");} if(mode==="summary"&&canvas._bars){canvas._bars.forEach(function(b){if(x>=b.x&&x<=b.x+b.w)d=b;}); if(d)tt.innerHTML="<b>"+d.label+"</b><br>"+formatINR(d.value);} if(!d){tt.style.display="none";return;} tt.style.display="block"; tt.style.left=Math.min(e.clientX+12,window.innerWidth-260)+"px"; tt.style.top=Math.max(e.clientY-18,10)+"px";}
    if(jc){jc.addEventListener("mousemove",function(e){move(jc,"journey",e);}); jc.addEventListener("mouseleave",function(){tt.style.display="none";});}
    if(sc){sc.addEventListener("mousemove",function(e){move(sc,"summary",e);}); sc.addEventListener("mouseleave",function(){tt.style.display="none";});}
  });
})();
